services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - stock-prediction-service
      - user-management-service
      - service-discovery
    environment:
      - SERVICE_DISCOVERY_URL=http://service-discovery:8500
    networks:
      - stock-net


  stock-prediction-service:
    build: ./stock-prediction-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - service-discovery
    environment:
      - SERVICE_DISCOVERY_URL=http://service-discovery:8500
      - SERVICE_NAME=stock-prediction-service
      - SERVICE_ADDRESS=stock-prediction-service
      - SERVICE_PORT=5000
    networks:
      - stock-net


  user-management-service:
    build: ./user-management-service
    ports:
      - "5002:5002"
    depends_on:
      - postgres
      - redis
      - service-discovery
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=users_db
      - SERVICE_DISCOVERY_URL=http://service-discovery:8500
      - SERVICE_NAME=user-management-service
      - SERVICE_ADDRESS=user-management-service
      - SERVICE_PORT=5002
    networks:
      - stock-net


  service-discovery:
    build: ./service-discovery
    ports:
      - "8500:8500"
    networks:
      - stock-net

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - stock-net

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    networks:
      - stock-net

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - stock-net

networks:
  stock-net:

volumes:
  pgdata:
  mongodata:
  proto:
