global:
  scrape_interval: 15s  # How often to scrape targets by default

scrape_configs:
  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'

  - job_name: 'stock_prediction_service'
    static_configs:
      - targets:
          - 'stock-prediction-service-1:5000'
          - 'stock-prediction-service-2:5000'
    metrics_path: '/metrics'

  - job_name: 'user_management_service'
    static_configs:
      - targets:
          - 'user-management-service-1:5002'
          - 'user-management-service-2:5002'
    metrics_path: '/metrics'

  - job_name: 'service_discovery'
    static_configs:
      - targets: ['service-discovery:8500']
    metrics_path: '/metrics'